### ISSUE TITLE
Parameters are not editable

### ISSUE THREAD

**Issue by joshwalawender** [KeckObservatory/LRIS_Focus_GUI#6]
The six parameters in the upper left corner of the UI window (center position, step size, and number of steps for red and blue respectively) do not appear to be editable by the user.  

If we do enable that, it would be good to put in some sort of message about the edge of the blue focus range since observers are likely to try to set a range which exceeds the blue focus stage's ability at some point.

**Comment by lucarizzi** [comment]
I am afraid this is a difficult problem. It is related to the way that our very old Solaris vnc desktop interpret the pyqt  instructions. 
The parameters are editable on Linux and on Mac. 

Not sure I have an easy solution, maybe we have to wait for the vm-Lris vnc server.

**Comment by joshwalawender** [comment]
> maybe we have to wait for the vm-Lris vnc server

I think that's a better solution than trying to add some hack to make it work with Solaris.  Closing.
